remote_theme: mmistakes/minimal-mistakes
baseurl: "/rnn-time-to-event"
url: "https://manelmc.github.io"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
header:
  image: /assets/LSTM3-chain-2.png
